title: 'Shri Hanumana Puja: Electromagnetic Force'
date: '1990-08-31'
location: Schwetzingen Palace, Schwetzingen (Germany)
amruta_url: https://www.amruta.org/1990/08/31/shri-hanumana-puja-frankfurt-1990/
language: en
videos:
- slug: Hanumana-Puja-Schwetzingen-Frankfurt-Germany-DP
  title: Hanumana Puja Schwetzingen Frankfurt Germany DP
  vimeo_url: https://vimeo.com/109922061/e754162a89
- slug: Hanumana-Puja-Talk
  title: Hanumana Puja Talk
  vimeo_url: https://vimeo.com/88510771/48dbe38ae6
