title: 'Shri Hanumana Puja: Electromagnetic Force'
date: '1990-08-31'
location: Schwetzingen Palace, Schwetzingen (Germany)
amruta_url: https://www.amruta.org/1990/08/31/shri-hanumana-puja-frankfurt-1990/
language: en
videos:
- slug: Hanumana-Puja-Schwetzingen-Frankfurt-Germany-DP
  title: Hanumana Puja Schwetzingen Frankfurt Germany DP
  video_ref: r1XFQVW0JTQUYaBEheTx1TWFhRUUI
- slug: Hanumana-Puja-Talk
  title: Hanumana Puja Talk
  video_ref: r1WhEITFEQEUlZU0BIGlZaUF1ZSw
