title: 'Christmas Puja: Become Thoughtlessly Aware'
date: '1998-12-25'
location: Ganapatipule (India)
amruta_url: https://www.amruta.org/1998/12/25/christmas-puja-1998/
language: en
videos:
- slug: Christmas-Puja
  title: Christmas Puja
  video_ref: r1AVQWWkYEREcZA0hXTB1YWFBZVEE
- slug: Christmas-Puja-Talk
  title: Christmas Puja Talk
  video_ref: r1Ug8SXhVWTEpJUEhWSR1YWFBZVEE
