title: 'Christmas Puja: Become Thoughtlessly Aware'
date: '1998-12-25'
location: Ganapatipule (India)
amruta_url: https://www.amruta.org/1998/12/25/christmas-puja-1998/
language: en
videos:
- slug: Christmas-Puja
  title: Christmas Puja
  vimeo_url: https://vimeo.com/251129058/b441f23b8d
- slug: Christmas-Puja-Talk
  title: Christmas Puja Talk
  vimeo_url: https://vimeo.com/251129009/1d994a7fc7
