title: 'Shri Ganesha Puja: Ritualism is not innocence'
date: '1993-09-19'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1993/09/19/ganesha-puja-cabella-1993/
language: en
videos:
- slug: Ganesha-Puja
  title: Ganesha Puja
  video_ref: r1V15GXxFREBEeBUhdTB5WWlRbUkA
- slug: Ganesha-Puja-Talk
  title: Ganesha Puja Talk
  video_ref: r1Vl1GChZUR0BIV0hcQBtSWlRbUkA
