title: 'Adi Shakti Puja: Humanity has to be saved through you and nobody else'
date: '2001-06-03'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/2001/06/03/shri-adi-shakti-puja-2001/
language: en
videos:
- slug: Adi-Shakti-Puja-Cabella-Italy-DP-RAW
  title: Adi Shakti Puja Cabella Italy DP-RAW
  video_ref: r1FVAKQwpCVEJCG05TVkkYUlNQWFFC
- slug: Adi-Shakti-Puja-Talk-Cabella-Italy-DP-RAW
  title: Adi Shakti Puja Talk Cabella Italy DP-RAW
  video_ref: r1QQdVQlhEBxZFTk5XWEgYUlNQWFFC
