title: The Spirit is the light
date: '1986-05-23'
location: Colegio Mayor Universitario Isabel de Espana, Madrid (Spain)
amruta_url: https://www.amruta.org/1986/05/23/2nd-public-program-in-madrid-1986/
language: en
videos:
- slug: The-Spirit-Is-The-Light
  title: The Spirit Is The Light
  vimeo_url: https://vimeo.com/704364514/89df53a875
