title: 'Guru Puja: The Statutes of the Lord'
date: '1980-07-27'
location: Temple of All Faiths, Hampstead (England)
amruta_url: https://www.amruta.org/1980/07/27/guru-puja-1980/
language: en
videos:
- slug: Shri-Guru-Puja
  title: Shri Guru Puja
  vimeo_url: https://vimeo.com/1053731319/f11dece99c
