title: 'Shri Ganesha Puja: The Innate Maryadas'
date: '1991-04-14'
location: Canberra Ashram, Canberra (Australia)
amruta_url: https://www.amruta.org/1991/04/14/shri-ganesha-puja-in-canberra-1991/
language: en
videos:
- slug: Ganesha-Puja
  title: Ganesha Puja
  video_ref: r1AwhGWhUEQhUVB0hdSRlZWlRbUkA
  sync: primary
- slug: Shri-Ganesha-Puja
  title: Shri Ganesha Puja
  video_ref: r1AVVFURJVFhUcU0heSBRTWlRbUkA
  sync: derived
