title: 'Mahashivaratri Puja: Four Nadis of the Heart'
date: '1991-02-16'
location: Chianciano Terme (Italy)
amruta_url: https://www.amruta.org/1991/02/16/mahashivaratri-puja-1991/
language: en
videos:
- slug: Mahashivaratri-Puja
  title: Mahashivaratri Puja
  video_ref: r1XF0XXkBaQUFLUUheSBhXWVFeV0Q
- slug: Mahashivaratri-Puja-CAM-2
  title: Mahashivaratri Puja CAM 2
  video_ref: r1BlpCWkIDFhAZVkhXQB9XWVFeV0Q
