title: 'Mahashivaratri Puja: Four Nadis of the Heart'
date: '1991-02-16'
location: Chianciano Terme (Italy)
amruta_url: https://www.amruta.org/1991/02/16/mahashivaratri-puja-1991/
language: en
videos:
- slug: Mahashivaratri-Puja
  title: Mahashivaratri Puja
  vimeo_url: https://vimeo.com/766036511/0f24847c19
- slug: Mahashivaratri-Puja-CAM-2
  title: Mahashivaratri Puja CAM 2
  vimeo_url: https://vimeo.com/766036298/74cca6366c
