title: 'Sahasrara Puja: Jump Into the Ocean of Joy'
date: '1989-05-06'
location: Sorrento (Italy)
amruta_url: https://www.amruta.org/1989/05/06/sahasrara-puja-1989/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  video_ref: r1UV9DXEQETUBPUkheTB5TX1hbUkQ
- slug: Sahasrara-Puja-Talk
  title: Sahasrara Puja Talk
  video_ref: r1A1QRD0VbRhIYA0hcShVRXVNcVkQ
