title: 'Sahasrara Puja: Achieve The Perfect State'
date: '1993-05-09'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1993/05/09/sahasrara-puja-1993/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  vimeo_url: https://vimeo.com/337507814/9d8edd4342
- slug: Sahasrara-Day-Puja-Talk-Achieve-The-Perfect-State
  title: 'Sahasrara Day Puja Talk: Achieve The Perfect State'
  vimeo_url: https://vimeo.com/337507502/684f524dfa
