title: 'Sahasrara Puja: Achieve The Perfect State'
date: '1993-05-09'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1993/05/09/sahasrara-puja-1993/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  video_ref: r1V1hHXRAGEEtJWEhbSBVWWlRfUkA
- slug: Sahasrara-Day-Puja-Talk-Achieve-The-Perfect-State
  title: 'Sahasrara Day Puja Talk: Achieve The Perfect State'
  video_ref: r1BAoQXUZXE0cVV0hdSRhWWlRfUkA
