title: Give up Misidentifications
date: '1979-04-22'
location: Dollis Hill Ashram, London (England)
amruta_url: https://www.amruta.org/1979/04/22/give-up-misidentifications-dollis-hill-1979/
language: en
videos:
- slug: Talk-London-UK-DP-Opt-HD
  title: Talk London UK DP Opt HD
  video_ref: r1F1UOTVpFUEEVS05eWEwbUFpWXlBC
