title: 'Birthday Puja: You Can Do A Lot'
date: '2002-03-21'
location: New Delhi (India)
amruta_url: https://www.amruta.org/2002/03/21/birthday-puja-2002/
language: en
videos:
- slug: 79th-Birthday-Puja-Delhi-India-DP-RAW
  title: 79th Birthday Puja Delhi India DP-RAW
  vimeo_url: https://vimeo.com/1001935361/32e39a9636
- slug: 79th-Birthday-Puja-Talk-Delhi-India-DP-RAW
  title: 79th Birthday Puja Talk Delhi India DP-RAW
  vimeo_url: https://vimeo.com/1001935309/91101809c2
