title: 'Birthday Puja: You Can Do A Lot'
date: '2002-03-21'
location: New Delhi (India)
amruta_url: https://www.amruta.org/2002/03/21/birthday-puja-2002/
language: en
videos:
- slug: 79th-Birthday-Puja-Delhi-India-DP-RAW
  title: 79th Birthday Puja Delhi India DP-RAW
  video_ref: r1RVZaTQhNURBBHk5WWUoYUlNQWFFC
- slug: 79th-Birthday-Puja-Talk-Delhi-India-DP-RAW
  title: 79th Birthday Puja Talk Delhi India DP-RAW
  video_ref: r1QQZVRFFFUkRCFE5eX0oYUlNQWFFC
