title: 'Guru Puja: A Guru Should Be Humble And Wise'
date: '1997-07-20'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1997/07/20/guru-puja-1997/
language: en
videos:
- slug: Guru-Puja
  title: Guru Puja
  video_ref: r1BAhHXBcGEEVMVkhaSx9VU1JeWUE
- slug: Guru-Puja-Talk-A-Guru-Should-Be-Humble-And-Wise
  title: 'Guru Puja Talk: A Guru Should Be Humble And Wise'
  video_ref: r1AA4VWkYERUpJU0hWSxlVU1JeWUE
