title: 'Guru Puja: A Guru Should Be Humble And Wise'
date: '1997-07-20'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1997/07/20/guru-puja-1997/
language: en
videos:
- slug: Guru-Puja
  title: Guru Puja
  vimeo_url: https://vimeo.com/286394225/7a6edc53da
- slug: Guru-Puja-Talk-A-Guru-Should-Be-Humble-And-Wise
  title: 'Guru Puja Talk: A Guru Should Be Humble And Wise'
  vimeo_url: https://vimeo.com/286394429/2d90f23abe
