title: 'Guru Puja: Gurus who belong to the collective'
date: '1993-07-04'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1993/07/04/guru-puja-1993/
language: en
videos:
- slug: Guru-Puja
  title: Guru Puja
  video_ref: r1BltEXEJVFBZIWUhYTR5TWFhRWUI
- slug: Guru-Puja-Talk-Gurus-Who-Belong-To-The-Collective
  title: 'Guru Puja Talk: Gurus Who Belong To The Collective'
  video_ref: r1VwpHCEFWFxUbAkhbSx9QWFhRWUI
