title: After Self-Realization, You Must Master It
date: '1983-10-14'
location: Old Cambridge Baptist Church, Boston (United States)
amruta_url: https://www.amruta.org/1983/10/14/public-program-175/
language: en
videos:
- slug: Public-Program-Boston-USA-DP-RAW
  title: Public Program Boston USA DP-RAW
  video_ref: r1XFxHW0VVTBEfA0hZShpZUldQWEo
