title: All is so Beautifully Made
date: '1982-04-22'
location: Hampstead Friends Meeting House, Hampstead (England)
amruta_url: https://www.amruta.org/1982/04/22/all-is-so-beautifully-made-hampstead-1982/
language: en
videos:
- slug: All-Is-So-Beautifully-Made-Hampstead-Other-Source-NITL
  title: All Is So Beautifully Made Hampstead Other Source NITL
  video_ref: r1AFlCWEYBTBFLB0hXQRVTXVdYVkU
