title: How to get the connection with the Divine power
date: '1990-06-03'
location: Miami (United States)
amruta_url: https://www.amruta.org/1990/06/03/public-program-1-in-miami-1990/
language: en
videos:
- slug: How-to-get-the-connection-with-the-Divine-power
  title: How to get the connection with the Divine power
  vimeo_url: https://vimeo.com/1136433756/6fdd62319f
