title: 'Shri Durga Puja: Mind is just like a donkey'
date: '1982-09-26'
location: Vienna (Austria)
amruta_url: https://www.amruta.org/1982/09/26/shri-durga-puja-vienna-1982/
language: en
videos:
- slug: Durga-Puja-P1
  title: Durga Puja P1
  vimeo_url: https://vimeo.com/158650231/7bfce1b54d
- slug: Durga-Puja-P2
  title: Durga Puja P2
  vimeo_url: https://vimeo.com/88526297/b176e640ae
- slug: Durga-Puja-Talk-Mind-Is-Just-Like-A-Donkey
  title: 'Durga Puja Talk: Mind Is Just Like A Donkey'
  vimeo_url: https://vimeo.com/88513297/0ad03b90c1
