title: 'Shri Durga Puja: Mind is just like a donkey'
date: '1982-09-26'
location: Vienna (Austria)
amruta_url: https://www.amruta.org/1982/09/26/shri-durga-puja-vienna-1982/
language: en
videos:
- slug: Durga-Puja-P1
  title: Durga Puja P1
  video_ref: r1AVhBC0UHFhVPVkheSh9RX1dQVEI
- slug: Durga-Puja-P2
  title: Durga Puja P2
  video_ref: r1CRVZQFQQRRpQBUBOFFNcU11ZSw
- slug: Durga-Puja-Talk-Mind-Is-Just-Like-A-Donkey
  title: 'Durga Puja Talk: Mind Is Just Like A Donkey'
  video_ref: r1XRdZTQBGQ0kAV0BOFFNZUF1ZSw
