title: 'Shri Ekadasha Rudra Puja: Ekadasha Principle is built-in the Void'
date: '1988-06-08'
location: Moedling (Austria)
amruta_url: https://www.amruta.org/1988/06/08/shri-ekadesha-rudra-puja-1988/
language: en
videos:
- slug: Ekadasha-Rudra-Puja
  title: Ekadasha Rudra Puja
  video_ref: r1UFRMCkADEEtJA0heThhRWlZeWEI
- slug: Ekadasha-Rudra-Puja-Talk
  title: Ekadasha Rudra Puja Talk
  video_ref: r1VFlCXUIHQURLVkhWTBVYU1deWEI
