title: England has to become Jerusalem
date: '1982-06-22'
location: Reading Civic Centre (demolished), Reading (England)
amruta_url: https://www.amruta.org/1982/06/22/public-program-reading-1982/
language: en
videos:
- slug: England-has-to-become-Jerusalem-1
  title: England has to become Jerusalem 1
  vimeo_url: https://vimeo.com/916418315/dca471d4ae
- slug: England-has-to-become-Jerusalem-2
  title: England has to become Jerusalem 2
  vimeo_url: https://vimeo.com/88520254/54e83507f4
- slug: England-has-to-become-Jerusalem-3
  title: England has to become Jerusalem 3
  vimeo_url: https://vimeo.com/88520241/ec4399073e
- slug: yogi-intro-Public-Program
  title: yogi intro Public Program
  vimeo_url: https://vimeo.com/88504933/a3134fd312
