title: England has to become Jerusalem
date: '1982-06-22'
location: Reading Civic Centre (demolished), Reading (England)
amruta_url: https://www.amruta.org/1982/06/22/public-program-reading-1982/
language: en
videos:
- slug: England-has-to-become-Jerusalem-1
  title: England has to become Jerusalem 1
  video_ref: r1AA1ADUVVQRJOBUhaSB5ZW1VeUEo
- slug: England-has-to-become-Jerusalem-2
  title: England has to become Jerusalem 2
  video_ref: r1WBJeRFdGS0hVUkBNGFNaU11ZSw
- slug: England-has-to-become-Jerusalem-3
  title: England has to become Jerusalem 3
  video_ref: r1CUdeRFtMQBkCAkBIGVNaU11ZSw
- slug: yogi-intro-Public-Program
  title: yogi intro Public Program
  video_ref: r1XkVaEARBQBxSBkBKHlheUV1ZSw
