title: 'Birthday Puja: A Great Day in History'
date: '1981-03-21'
location: Sydney (Australia)
amruta_url: https://www.amruta.org/1981/03/21/birthday-puja-1981-sydney/
language: en
videos:
- slug: Birthday-Puja
  title: Birthday Puja
  video_ref: r1VwkVWEFQRkBMBUhaSB9XWlNdWUE
- slug: Birthday-Puja-Talk
  title: Birthday Puja Talk
  video_ref: r1XVoQCxUBQEFMUkhfQB1YWlNdWUE
