title: 'Shri Vishnumaya Puja: Stop Feeling Guilty'
date: '1992-09-20'
location: Shawnee on Delaware (United States)
amruta_url: https://www.amruta.org/1992/09/20/shri-vishnumaya-puja-shawneee-1992/
language: en
videos:
- slug: Vishnumaya-Puja-Pennsylvania-USA-DP-RAW
  title: Vishnumaya Puja Pennsylvania USA DP-RAW
  video_ref: r1VApHUUNWREUbBUhYThRRUlFQWEs
- slug: Vishnumaya-Puja-Talk-Pennsylvania-USA-DP-RAW
  title: Vishnumaya Puja Talk Pennsylvania USA DP-RAW
  video_ref: r1VlpCWRYBFBYVWUhfSxRRUlFQWEs
