title: 'Sahasrara Puja: At Sahasrara you stand on Truth and go beyond Dharma'
date: '1997-05-04'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1997/05/04/sahastrara-puja-1997/
language: en
videos:
- slug: Sahasrara-Puja-Cabella-Italy-DP-RAW
  title: Sahasrara Puja Cabella Italy DP-RAW
  video_ref: r1VA9CXUJbExBMWUhXTRxVWFRRU0s
- slug: Sahasrara-Puja-Talk-Cabella-Italy-DP-RAW
  title: Sahasrara Puja Talk Cabella Italy DP-RAW
  video_ref: r1UFoRWkZSFkBOU0hZQR1VWFRRU0s
