title: 8th Day of Navaratri, Talk to English Yogis on Style and Content
date: '1989-10-06'
location: Butlins Grand Hotel, Margate (England)
amruta_url: https://www.amruta.org/1989/10/06/talk-to-english-yogis-1989/
language: en
videos:
- slug: 8th-Day-Of-Navaratri
  title: 8th Day Of Navaratri
  video_ref: r1XFlCUENSEEYcVkhdQBlXXVJdVkA
