title: 'Sahasrara Puja: Realise Your Own Divinity'
date: '1991-05-05'
location: Ischia (Italy)
amruta_url: https://www.amruta.org/1991/05/05/sahastrara-puja-1991/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  vimeo_url: https://vimeo.com/126369360/9ca726d0c3
- slug: Sahasrara-Puja-Talk
  title: Sahasrara Puja Talk
  vimeo_url: https://vimeo.com/159690519/886eccc37e
