title: 'Sahasrara Puja: Realise Your Own Divinity'
date: '1991-05-05'
location: Ischia (Italy)
amruta_url: https://www.amruta.org/1991/05/05/sahastrara-puja-1991/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  video_ref: r1Vg9EDUJQQhJOWEhfTx5YXFJeU0I
- slug: Sahasrara-Puja-Talk
  title: Sahasrara Puja Talk
  video_ref: r1AFtHChcBEEUVWUhWSBhRU1dRVEI
