title: From Heart to Sahasrara
date: '1982-07-11'
location: Guildhall Theatre, Derby (England)
amruta_url: https://www.amruta.org/1982/07/11/from-heart-to-sahastrar-derby-1982/
language: en
videos:
- slug: From-Heart-to-Sahasrara
  title: From Heart to Sahasrara
  video_ref: r1VE1fRVMWEh9VV0BPFFFcU11ZSw
