title: 'Shri Ganesha Puja: How Far To Go With Children'
date: '1989-08-08'
location: Les Diablerets (Switzerland)
amruta_url: https://www.amruta.org/1989/08/08/shri-ganesha-puja-1989/
language: en
videos:
- slug: Ganesha-Puja
  title: Ganesha Puja
  video_ref: r1Uw1NXBBTFkcfVEhXQR5SWVVbUUE
- slug: Ganesha-Puja-Talk
  title: Ganesha Puja Talk
  video_ref: r1Ug0WDBFWREUUV0hcTxxXWllbUUE
