title: 'Shri Ganesha Puja: How Far To Go With Children'
date: '1989-08-08'
location: Les Diablerets (Switzerland)
amruta_url: https://www.amruta.org/1989/08/08/shri-ganesha-puja-1989/
language: en
videos:
- slug: Ganesha-Puja
  title: Ganesha Puja
  vimeo_url: https://vimeo.com/203433388/524c1d59a6
- slug: Ganesha-Puja-Talk
  title: Ganesha Puja Talk
  vimeo_url: https://vimeo.com/203806163/69614eeba7
