title: How to become a realized soul?
date: '1988-07-20'
location: Hotel Dann Colonial, Bogota (Colombia)
amruta_url: https://www.amruta.org/1988/07/20/first-public-program-in-bogota-1988/
language: en
videos:
- slug: How-to-become-a-realized-soul-Bogota-Colombia-DP-RAW
  title: How to become a realized soul? Bogota Colombia DP-RAW
  video_ref: r1SgcKRA9GVU0QS05QWUkYV1hWX1BC
