title: 'Guru Puja: Awakening the Principle of Guru'
date: '1983-07-24'
location: Lodge Hill
amruta_url: https://www.amruta.org/1983/07/24/guru-puja-1983/
language: en
videos:
- slug: Talk
  title: Talk
