title: 'Public Program: Science/Trigunatmika'
date: '1975-03-29'
location: Mumbai (India)
amruta_url: https://www.amruta.org/1975/03/29/sciencetrigunatmika-1975-hindi/
language: en
videos:
- slug: Public-Program-Sweet-Home-Hall-Dadar-Mumbai-Hindi-Pasq
  title: Public Program Sweet Home Hall Dadar Mumbai Hindi Pasq
  vimeo_url: https://vimeo.com/1065815961/faed98941e
