title: 'Shri Krishna Puja: Ananya Bhakti'
date: '2001-07-29'
location: Nirmal Nagari, Canajoharie (United States)
amruta_url: https://www.amruta.org/2001/07/29/shri-krishna-puja-new-york-2001/
language: en
videos:
- slug: Krishna-Puja
  title: Krishna Puja
  video_ref: r1XBALQVVAEhVUUkBIFFNeVVxZSw
- slug: Krishna-Puja-Talk
  title: Krishna Puja Talk
  video_ref: r1XEBaQAAXFxtVBUBKH1NYUF1ZSw
