title: 'Shri Ganesha Puja: Establishing Shri Ganesha Principle'
date: '1986-09-07'
location: YMCA – Camp Marston, San Diego (United States)
amruta_url: https://www.amruta.org/1986/09/07/shri-ganesha-puja-1986/
language: en
videos:
- slug: Ganesha-Puja-Talk
  title: Ganesha Puja Talk
  video_ref: r1BFsSDENXE0RMAkhaShhUWlZaWEE
  sync: derived
- slug: Ganesha-Puja
  title: Ganesha Puja
  video_ref: r1B1gSXBEHFhEaBEhaQR5TWlZaWEE
  sync: primary
