title: Christmas And Its Relationship To Lord Jesus
date: '1979-12-10'
location: Caxton Hall, London (England)
amruta_url: https://www.amruta.org/1979/12/10/christmas-and-its-relationship-to-lord-jesus-1979-2/
language: en
videos:
- slug: The-Incarnation-Of-Christ
  title: The Incarnation Of Christ
  video_ref: r1BF0XWEQGEUUUVEheSxlXX1lbWUQ
