title: 'Guru Puja: Establishing the Guru Principle and Havan After Puja'
date: '1982-07-04'
location: Nirmala Palace – Nightingale Lane Ashram, London (England)
amruta_url: https://www.amruta.org/1982/07/04/shri-adi-guru-puja-1982/
language: en
videos:
- slug: Guru-Puja
  title: Guru Puja
  vimeo_url: https://vimeo.com/254918185/0ec8c021be
- slug: Guru-Puja-Part-2-and-Havan-London-NITL-RAW
  title: Guru Puja Part 2 and Havan London NITL-RAW
  vimeo_url: https://vimeo.com/916428855/39052044ed
- slug: Guru-Puja-Talk-Establishing-The-Guru-Principle
  title: 'Guru Puja Talk: Establishing The Guru Principle'
  vimeo_url: https://vimeo.com/254917975/2b64a09af0
- slug: Presents-After-Shri-Guru-Puja
  title: Presents After Shri Guru Puja
  vimeo_url: https://vimeo.com/234752304/dcfa577bfa
