title: 'Guru Puja: Establishing the Guru Principle and Havan After Puja'
date: '1982-07-04'
location: Nirmala Palace – Nightingale Lane Ashram, London (England)
amruta_url: https://www.amruta.org/1982/07/04/shri-adi-guru-puja-1982/
language: en
videos:
- slug: Guru-Puja
  title: Guru Puja
  video_ref: r1AA5FW0QBTRBIUUhaQRxZW1hcVEE
- slug: Guru-Puja-Part-2-and-Havan-London-NITL-RAW
  title: Guru Puja Part 2 and Havan London NITL-RAW
  video_ref: r1AQlAXURQQEMUUkhaTBVZWFVeUEo
- slug: Guru-Puja-Talk-Establishing-The-Guru-Principle
  title: 'Guru Puja Talk: Establishing The Guru Principle'
  video_ref: r1VQoVUEQDQUVPU0haThRWW1hcVEE
- slug: Presents-After-Shri-Guru-Puja
  title: Presents After Shri Guru Puja
  video_ref: r1BAoWXkNXFBVOBUhbSR5TX1ZcUkE
