title: The Revival of Indian Spirituality
date: '1998-12-14'
location: New Delhi (India)
amruta_url: https://www.amruta.org/1998/12/14/the-revival-of-indian-spirituality-1998-new-delhi/
language: en
videos:
- slug: The-Revival-of-Indian-Spirituality
  title: The Revival of Indian Spirituality
  video_ref: r1BAgRXkxVE0IVU0hfShRQWldbUEI
- slug: The-Revival-Of-Indian-Spirituality-Delhi-NITL-RAW
  title: The Revival Of Indian Spirituality Delhi NITL-RAW
  video_ref: r1BghNWBVTFEZIBEhdShtXX1hbUEo
