title: 'Sahasrara Puja: The Will of God'
date: '1992-05-10'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1992/05/10/sahastrara-puja-1992/
language: en
videos:
- slug: Sahasrara-Puja-Cabella-NITL-RAW
  title: Sahasrara Puja Cabella NITL-RAW
  video_ref: r1U1lGW0NVQBIdBEhcQRlZUlldUUo
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  video_ref: r1A1lCWRcBRkMeU0heTBRWWlRfUkA
- slug: Sahasrara-Day-Talk-The-Will-of-God
  title: 'Sahasrara Day Talk: The Will of God'
  video_ref: r1VQhECEAEREVOVEheThhWWlRfUkA
