title: 'Sahasrara Puja: To Break Sahasrara'
date: '2001-05-06'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/2001/05/06/sahasrara-puja-2001/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  video_ref: r1VVwRXUNXFxVMUkhcTRlSWVleUkA
- slug: Sahasrara-Puja-Talk-To-Break-Sahasrara
  title: 'Sahasrara Puja Talk: To Break Sahasrara'
  video_ref: r1BltEXBJSQEYbBUhYTB1SWVleUkA
