title: 'Sahasrara Puja: To Break Sahasrara'
date: '2001-05-06'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/2001/05/06/sahasrara-puja-2001/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  vimeo_url: https://vimeo.com/336833443/3afb574e00
- slug: Sahasrara-Puja-Talk-To-Break-Sahasrara
  title: 'Sahasrara Puja Talk: To Break Sahasrara'
  vimeo_url: https://vimeo.com/336833057/d6550f507c
