title: 'Shri Virata Puja: First of all, you have to rise above your ego'
date: '1999-09-05'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1999/09/05/shri-virata-puja-cabella-1999/
language: en
videos:
- slug: Virata-Puja-Cabella-Italy-DP-RAW
  title: Virata Puja Cabella Italy DP-RAW
  video_ref: r1ElRVRQtDBhBDHk5eW0AZUlNQWFFC
- slug: Virata-Puja-Talk-Cabella-Italy-DP-RAW
  title: Virata Puja Talk Cabella Italy DP-RAW
  video_ref: r1SgNfFl4RVRZLGU5XW0kYUlNQWFFC
