title: 'Shri Ganesha Puja: Project your innocence to others'
date: '1995-09-10'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1995/09/10/shri-ganesha-puja-cabella-1995/
language: en
videos:
- slug: Ganesha-Puja
  title: Ganesha Puja
  video_ref: r1UFxCDEwEEEtIBUhZTRlQWlFdUkQ
- slug: Ganesha-Puja-Talk
  title: Ganesha Puja Talk
  video_ref: r1Bl1NW0JWREdOUUhcTR5WWFBdVkQ
