title: 'Shri Ganesha Puja: Project your innocence to others'
date: '1995-09-10'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1995/09/10/shri-ganesha-puja-cabella-1995/
language: en
videos:
- slug: Ganesha-Puja
  title: Ganesha Puja
  vimeo_url: https://vimeo.com/735001446/de8ef8e605
- slug: Ganesha-Puja-Talk
  title: Ganesha Puja Talk
  vimeo_url: https://vimeo.com/775127343/0c4146291c
