title: 'Adi Shakti Puja: The steadiness of the mind is very important for the marriages'
date: '1988-12-11'
location: Residence of Madhukar Dhumal, Rahuri (India)
amruta_url: https://www.amruta.org/1988/12/11/shri-adi-shakti-puja-rahuri-1988/
language: en
videos:
- slug: Adi-Shakti-Puja-Cam-2
  title: Adi Shakti Puja Cam 2
  video_ref: r1AF9BX0IAREAeV0hcTR1XWFdbWUc
- slug: Adi-Shakti-Puja-Cam-1
  title: Adi Shakti Puja Cam 1
  video_ref: r1BFsXWhZbTBFOBEhcQB9VWFdbWUc
- slug: Adi-Shakti-Puja-Talk-Detachment
  title: 'Adi Shakti Puja Talk: Detachment'
  video_ref: r1UlkWUBABQkMZVkhYTBxWW1dbWUc
other_languages:
- mr
