title: 'Shri Ekadasha Rudra Puja: We have to drop out many things'
date: '1983-09-17'
location: Judy Gaddy's Apartment, New York (United States)
amruta_url: https://www.amruta.org/1983/09/17/ekadesha-rudra-puja-new-york-1983/
language: en
videos:
- slug: Ekadasha-Rudra-Puja
  title: Ekadasha Rudra Puja
  video_ref: r1AwlHWRdaFBAeVUhYSBVVWlRbUkA
- slug: Ekadasha-Rudra-Puja-Talk
  title: Ekadasha Rudra Puja Talk
  video_ref: r1WhVcQgFARxxVVkBBH1VcUV1ZSw
