title: 'Shri Ekadasha Rudra Puja: We have to drop out many things'
date: '1983-09-17'
location: Judy Gaddy's Apartment, New York (United States)
amruta_url: https://www.amruta.org/1983/09/17/ekadesha-rudra-puja-new-york-1983/
language: en
videos:
- slug: Ekadasha-Rudra-Puja
  title: Ekadasha Rudra Puja
  vimeo_url: https://vimeo.com/333504817/43ca8c03ef
- slug: Ekadasha-Rudra-Puja-Talk
  title: Ekadasha Rudra Puja Talk
  vimeo_url: https://vimeo.com/88506428/14145c65a6
