title: Talk on Innocence & Musical Program (Morning)
date: '1987-01-02'
location: Ganapatipule (India)
amruta_url: https://www.amruta.org/1987/01/02/innocence-and-ganesha-ganapatipule-1987/
language: en
videos:
- slug: Morning-Musical-Program-Ganapatipule-India-DP-RAW
  title: Morning Musical Program Ganapatipule India DP-RAW
  video_ref: r1UVhFURJWRkpPU0hfQB5RXlNZUEQ
