title: 'Devi Puja: Nothing to discuss in Sahaja Yoga'
date: '1989-12-17'
location: Alibag (India)
amruta_url: https://www.amruta.org/1989/12/17/nothing-to-discuss-in-sahaja-yoga-alibag-1989/
language: en
videos:
- slug: Puja-Alibag
  title: Puja Alibag
  video_ref: r1UAhNXUUEEUEUBEhaSh5YWlRbUkA
- slug: Puja-Talk
  title: Puja Talk
  video_ref: r1BloXUEBaEUMVB0hfQBxSWlRbUkA
