title: 'Birthday Puja: Be Sweet, Loving and Peaceful'
date: '1984-03-22'
location: Juhu, Mumbai (India)
amruta_url: https://www.amruta.org/1984/03/22/birthday-puja-1984/
language: en
other_languages:
- mr
videos:
- slug: Birthday-Puja-Be-Sweet
  title: 'Birthday Puja: Be Sweet'
  video_ref: r1AFhGDUNVQEUcVEhWSxRYUlJbWEA
- slug: Birthday-Puja-Talk-Be-Sweet
  title: 'Birthday Puja Talk: Be Sweet'
  video_ref: r1VFlGDU1SF0pMU0heQB9ZUlJbWEA
