title: 'Bhavasagara Puja: Meditation will protect you'
date: '1991-04-06'
location: Brisbane (Australia)
amruta_url: https://www.amruta.org/1991/04/06/shri-bhavasagara-puja-1991/
language: en
videos:
- slug: Bhavasagara-Puja-Brisbane-NITL-RAW
  title: Bhavasagara Puja Brisbane NITL-RAW
  vimeo_url: https://vimeo.com/908566903/b73a63b3df
- slug: Bhavasagara-Puja-Talk-Meditation-Will-Protect-You
  title: 'Bhavasagara Puja Talk: Meditation Will Protect You'
  vimeo_url: https://vimeo.com/88508314/ed32a7b98d
