title: 'Mahashivaratri Puja: You are extremely powerful'
date: '1992-02-29'
location: Glenrock Scout Camp, Newcastle (Australia)
amruta_url: https://www.amruta.org/1992/02/29/mahashivaratri-puja-1992/
language: en
videos:
- slug: Maha-Shiva-Puja
  title: Maha Shiva Puja
  vimeo_url: https://vimeo.com/777195384/5a98347b90
- slug: Maha-Shiva-Puja-Talk-Newcastle-Australia-DP-RAW
  title: Maha Shiva Puja Talk Newcastle Australia DP-RAW
  vimeo_url: https://vimeo.com/777194609/1009122734
