title: 'Shri Ganesha Puja: Shri Ganesha and His Qualities'
date: '1991-09-15'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1991/09/15/shri-ganesha-puja-cabella-1991/
language: en
videos:
- slug: Ganesha-Puja-Cabella-Italy-DP-RAW
  title: Ganesha Puja Cabella Italy DP-RAW
  vimeo_url: https://vimeo.com/704364780/2279201ef5
- slug: Ganesha-Puja-Talk
  title: Ganesha Puja Talk
  vimeo_url: https://vimeo.com/775126953/1e07eed986
