title: 'Devi Puja: Mother you be in our brain'
date: '1983-03-04'
location: Adelaide (Australia)
amruta_url: https://www.amruta.org/1983/03/04/devi-puja-in-adelaide-1983/
language: en
videos:
- slug: Puja
  title: Puja
  video_ref: r1UFsVW0UHTBcaAkheTh9SWVJbUkI
- slug: Devi-Puja-Talk-Mother-you-be-in-our-brain
  title: 'Devi Puja Talk: Mother you be in our brain'
  video_ref: r1XkdbEFVGSkwCUUBOGFBaUV1ZSw
