title: 'Devi Puja: Mother you be in our brain'
date: '1983-03-04'
location: Adelaide (Australia)
amruta_url: https://www.amruta.org/1983/03/04/devi-puja-in-adelaide-1983/
language: en
videos:
- slug: Puja
  title: Puja
  vimeo_url: https://vimeo.com/133333271/c7d9e12a75
- slug: Devi-Puja-Talk-Mother-you-be-in-our-brain
  title: 'Devi Puja Talk: Mother you be in our brain'
  vimeo_url: https://vimeo.com/88500157/6ca937d232
