title: 'Sahasrara Puja: Consciousness and Evolution'
date: '1986-05-04'
location: Alpe Motta (Italy)
amruta_url: https://www.amruta.org/1986/05/04/sahasrara-puja-1986/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  video_ref: r1XA5HDUdXRUcYAkhZTB9QUlhfUEc
- slug: Sahasrara-Puja-Talk-Consciousness-And-Evolution
  title: 'Sahasrara Puja Talk: Consciousness And Evolution'
  video_ref: r1U1VFWEQGQ0MdA0hfQBlYXVhfUEc
