title: 'Sahasrara Puja: Consciousness and Evolution'
date: '1986-05-04'
location: Alpe Motta (Italy)
amruta_url: https://www.amruta.org/1986/05/04/sahasrara-puja-1986/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  vimeo_url: https://vimeo.com/417981256/c54053d3b9
- slug: Sahasrara-Puja-Talk-Consciousness-And-Evolution
  title: 'Sahasrara Puja Talk: Consciousness And Evolution'
  vimeo_url: https://vimeo.com/417979490/b006d01196
