title: 'Easter Puja: You Cannot Resurrect Yourself Without Controlling Agnya'
date: '2001-04-22'
location: Ataköy Marina Hotel, Istanbul (Turkey)
amruta_url: https://www.amruta.org/2001/04/22/easter-puja-2001/
language: en
videos:
- slug: Easter-Puja-Istanbul-Turkey-DP-RAW
  title: Easter Puja Istanbul Turkey DP-RAW
  video_ref: r1EgRZTF9AUUJGHU5SWUsfVF9TUFFC
- slug: Easter-Puja-Talk-Istanbul-Turkey-DP-RAW
  title: Easter Puja Talk Istanbul Turkey DP-RAW
  video_ref: r1RARVEF8QUUNBTE5QVk0fVF9TUFFC
