title: Arrival Talk
date: '1995-02-19'
location: Melbourne Airport, Melbourne (Australia)
amruta_url: https://www.amruta.org/1995/02/19/advice-to-yogis-at-melbourne-airport-1995/
language: en
videos:
- slug: Arrival-Talk
  title: Arrival Talk
  vimeo_url: https://vimeo.com/122433616/6cfdc75256
