title: 'Shri Fatima Puja: Women are responsible for the society'
date: '1993-05-18'
location: )
amruta_url: https://www.amruta.org/1993/05/18/shri-fatima-puja-1993/
language: en
videos:
- slug: Fatima-Puja
  title: Fatima Puja
  video_ref: r1AFsWWhdQQEFJB0haSxlXWlNdWUE
- slug: Fatima-Puja-Talk
  title: Fatima Puja Talk
  video_ref: r1UVhGXURWFhJOAkhcSxRUWlZaWEE
