title: Knots On The Three Channels
date: '1978-10-02'
location: Caxton Hall, London (England)
amruta_url: https://www.amruta.org/1978/10/02/knots-on-the-three-channels-caxton-hall-1978/
language: en
videos:
- slug: Knots-In-The-3-Channels-London-NITL-HD
  title: Knots In The 3 Channels London NITL HD
  video_ref: r1Uw0QCExTEUtIAEhXQRpYU1hYWUQ
