title: 'Sahasrara Puja: Continue To Live A Life of Reality'
date: '2004-05-09'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/2004/05/09/sahastrara-puja-2004/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  video_ref: r1VEYIQwMXSk8CAUBMFFRYVVxZSw
- slug: Sahasrara-Puja-Talk-Continue-To-Live-A-Life-Of-Reality
  title: 'Sahasrara Puja Talk: Continue To Live A Life Of Reality'
  video_ref: r1WBZYFwNGRUxYUkBAG1FeUV1ZSw
