title: Questions and Answers after Maha Sahasrara Day
date: '1984-05-06'
location: Château de Mesnières, Mesnières-en-Bray (France)
amruta_url: https://www.amruta.org/1984/05/06/advice-the-day-after-mahasaharara-puja-how-to-protect-ourselves/
language: en
videos:
- slug: Seminar-Day-2
  title: Seminar Day 2
  vimeo_url: https://vimeo.com/333510107/60b765eeb5
