title: 'Shri Saraswati Puja: The basis of all creativity is love'
date: '1983-01-14'
location: Dhule (India)
amruta_url: https://www.amruta.org/1983/01/14/shri-saraswati-puja-dhulia-1983/
language: en
videos:
- slug: Saraswati-Puja
  title: Saraswati Puja
  vimeo_url: https://vimeo.com/296205431/e8a436d603
- slug: Saraswati-Puja-Talk-Creativity
  title: 'Saraswati Puja Talk: Creativity'
  vimeo_url: https://vimeo.com/296205829/46c2ccbbdd
