title: 'Shri Saraswati Puja: The basis of all creativity is love'
date: '1983-01-14'
location: Dhule (India)
amruta_url: https://www.amruta.org/1983/01/14/shri-saraswati-puja-dhulia-1983/
language: en
videos:
- slug: Saraswati-Puja
  title: Saraswati Puja
  video_ref: r1VlxCDUJRQRIVBEheShlUWlNeWEE
- slug: Saraswati-Puja-Talk-Creativity
  title: 'Saraswati Puja Talk: Creativity'
  video_ref: r1AQgWCxcBRxAbVUhWSxVUWlNeWEE
