title: Christmas Puja
date: '2001-12-25'
location: Ganapatipule (India)
amruta_url: https://www.amruta.org/2001/12/25/christmas-puja-2001/
language: en
videos:
- slug: Christmas-Puja-Ganapatipule-NITL-RAW
  title: Christmas Puja Ganapatipule NITL-RAW
  vimeo_url: https://vimeo.com/916741580/1f9d5c51cd
- slug: Christmas-Puja
  title: Christmas Puja
  vimeo_url: https://vimeo.com/88440086/4953594bc7
- slug: Christmas-Puja-Talk
  title: Christmas Puja Talk
  vimeo_url: https://vimeo.com/88509605/fa974979a0
- slug: Christmas-Puja-Talk-Ganapatipule-NITL-RAW
  title: Christmas Puja Talk Ganapatipule NITL-RAW
  vimeo_url: https://vimeo.com/916741339/e2c33bc8c4
