title: Christmas Puja
date: '2001-12-25'
location: Ganapatipule (India)
amruta_url: https://www.amruta.org/2001/12/25/christmas-puja-2001/
language: en
videos:
- slug: Christmas-Puja-Ganapatipule-NITL-RAW
  title: Christmas Puja Ganapatipule NITL-RAW
  video_ref: r1AQ9FXBdXEUpLUEhfQRhQXlZeUEo
- slug: Christmas-Puja
  title: Christmas Puja
  video_ref: r1WxcLQFtAQBhYU0BPFVFaVVxZSw
- slug: Christmas-Puja-Talk
  title: Christmas Puja Talk
  video_ref: r1XBVQQ1tBRBQAAUBMHVdTUV1ZSw
- slug: Christmas-Puja-Talk-Ganapatipule-NITL-RAW
  title: Christmas Puja Talk Ganapatipule NITL-RAW
  video_ref: r1UQ9MChZRRhAfBEhWSh5QXlZeUEo
