title: 'Shri Mahakali Puja: The Culture Of The Spirit'
date: '1987-10-16'
location: Blutenburg Castle, Munich (Germany)
amruta_url: https://www.amruta.org/1987/10/16/shri-mahakali-puja-munich-1987/
language: en
videos:
- slug: Mahakali-Puja
  title: Mahakali Puja
  vimeo_url: https://vimeo.com/189926413/01bef436f8
- slug: Mahakali-Puja-Talk-The-Culture-Of-The-Spirit
  title: 'Mahakali Puja Talk: The Culture Of The Spirit'
  vimeo_url: https://vimeo.com/189925451/b6eebb045d
