title: 'Shri Mahakali Puja: The Culture Of The Spirit'
date: '1987-10-16'
location: Blutenburg Castle, Munich (Germany)
amruta_url: https://www.amruta.org/1987/10/16/shri-mahakali-puja-munich-1987/
language: en
videos:
- slug: Mahakali-Puja
  title: Mahakali Puja
  video_ref: r1XQpCWkAEEBEcUUhcSBlXWFhRWUI
- slug: Mahakali-Puja-Talk-The-Culture-Of-The-Spirit
  title: 'Mahakali Puja Talk: The Culture Of The Spirit'
  video_ref: r1AVlAWRYAEBYbA0heTBlUWFhRWUI
