title: 6th Day of Navaratri Celebrations, Shri Kundalini, Shakti and Shri Jesus
date: '1979-09-27'
location: Hinduja Auditorium, Mumbai (India)
amruta_url: https://www.amruta.org/1979/09/27/shri-kundalini-shakti-and-shri-jesus-bombay-1979/
language: hi
videos:
- slug: Kundalini-Aur-Yeshu-Krist-Mumbai-NITL-HD
  title: Kundalini Aur Yeshu Krist Mumbai NITL HD
  video_ref: r1FlANQQtDUREWHE5WW0kYUl1SXVFC
