title: 'Mahashivaratri Puja: Surrender'
date: '1994-03-14'
location: New Delhi (India)
amruta_url: https://www.amruta.org/1994/03/14/mahashivaratri-puja-1994/
language: en
videos:
- slug: Sadashiva-Puja
  title: Sadashiva Puja
  video_ref: r1BA1DX0RRQUtPV0hZSxxZW1hcVEE
- slug: Sadashiva-Puja-Talk
  title: Sadashiva Puja Talk
  video_ref: r1VA4QDxcEQkRJWEhXTR1ZW1hcVEE
