title: 'Mahashivaratri Puja: Surrender'
date: '1994-03-14'
location: New Delhi (India)
amruta_url: https://www.amruta.org/1994/03/14/mahashivaratri-puja-1994/
language: en
videos:
- slug: Sadashiva-Puja
  title: Sadashiva Puja
  vimeo_url: https://vimeo.com/254918126/6b843067aa
- slug: Sadashiva-Puja-Talk
  title: Sadashiva Puja Talk
  vimeo_url: https://vimeo.com/254918048/9d77fcfdb1
