title: 'Guru Puja: Gravity'
date: '1992-07-19'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1992/07/19/guru-puja-1992/
language: en
videos:
- slug: Guru-Puja
  title: Guru Puja
  video_ref: r1A1QQUEUHE0FJBUhdSh5QW1RbUkA
- slug: Guru-Puja-Talk-Gravity
  title: 'Guru Puja Talk: Gravity'
  video_ref: r1XVsVXRZXQhdJB0hZShlVWlRbUkA
