title: '11th Day of Navaratri: Put me in your Heart'
date: '1984-10-05'
location: Chelsham Road Ashram, London (England)
amruta_url: https://www.amruta.org/1984/10/05/put-me-in-your-heart-london-1984/
language: en
videos:
- slug: Put-Me-In-Your-Heart-Talk
  title: Put Me In Your Heart Talk
  video_ref: r1U1pNUBVWTBcfVUhWQRtUWlNeWEE
  sync: derived
- slug: Put-Me-In-Your-Heart
  title: Put Me In Your Heart
  video_ref: r1VVtDWUBRQBJOVEhZTB9SXlNeWEE
  sync: primary
