title: 'Mahashivaratri Puja: The importance of Shiva'
date: '1979-02-25'
location: Pune (India)
amruta_url: https://www.amruta.org/1979/02/25/puja-in-pune-marathi-1979/
language: en
videos:
- slug: Mahashivaratri-Puja
  title: Mahashivaratri Puja
  video_ref: r1XF0WUUUDERUZAEhZTBpVU1BeUEo
other_languages:
- mr
