title: 'Shri Pallas Athena Puja: You have to be sincere and honest'
date: '1993-04-26'
location: Sahaja Yoga Center in Athens, Athens (Greece)
amruta_url: https://www.amruta.org/1993/04/26/shri-pallas-athena-puja-athens-1993/
language: en
videos:
- slug: Athena-Puja-Greece-DP-RAW
  title: Athena Puja Greece DP-RAW
  vimeo_url: https://vimeo.com/802799126/e74b936e9a
- slug: Athena-Puja-Talk-Greece-DP-RAW
  title: Athena Puja Talk Greece DP-RAW
  vimeo_url: https://vimeo.com/802798970/36cae22051
