title: 'Shri Ganesha Puja: Innocence & Joy'
date: '1982-08-22'
location: House of Charles and Magda Mathys, Troinex (Switzerland)
amruta_url: https://www.amruta.org/1982/08/22/ganesha-puja-geneva-1982/
language: en
videos:
- slug: Ganesha-Puja-Troinex-Switzerland-DP
  title: Ganesha Puja Troinex Switzerland DP
  vimeo_url: https://vimeo.com/104932604/a847f7c385
- slug: Ganesha-Puja-Talk-Innocence-Joy
  title: 'Ganesha Puja Talk: Innocence & Joy'
  vimeo_url: https://vimeo.com/104929805/b63f0fb562
