title: Advice about Chakras
date: '1979-12-30'
location: CKP Hall, Mumbai (India)
amruta_url: https://www.amruta.org/1979/12/30/advice-about-chakras-mumbai-1979/
language: en
videos:
- slug: The-Meaning-of-love
  title: The Meaning of love
  vimeo_url: https://vimeo.com/1053726666/1237ee01e5
