title: Advice about Chakras
date: '1979-12-30'
location: CKP Hall, Mumbai (India)
amruta_url: https://www.amruta.org/1979/12/30/advice-about-chakras-mumbai-1979/
language: en
videos:
- slug: The-Meaning-of-love
  title: The Meaning of love
  video_ref: r1RgBdRAwRVUZBHE5RWU8bU11SXVFC
