title: 'Shri Lakshmi Puja: Sea is your grandfather'
date: '1991-12-29'
location: Chalmala, Alibag (India)
amruta_url: https://www.amruta.org/1991/12/29/shri-lakshmi-puja-in-alibag-1991/
language: en
videos:
- slug: Lakshmi-Puja-Marathi-English-Alibag-India-DP
  title: Lakshmi Puja Marathi English Alibag India DP
  vimeo_url: https://vimeo.com/804794404/741d49cfac
- slug: Lakshmi-Puja-Talk-Marathi-English-Alibag-India-DP
  title: Lakshmi Puja Talk Marathi English Alibag India DP
  vimeo_url: https://vimeo.com/804794388/da5971acd9
