title: 'Birthday Puja: Try to save as many as possible & Havan'
date: '1983-03-30'
location: Mumbai (India)
amruta_url: https://www.amruta.org/1983/03/30/celebration-of-birthday-in-bombay-1983/
language: en
videos:
- slug: Birthday-Puja-and-Havan
  title: Birthday Puja and Havan
  video_ref: r1UVkWW0UGExAeVkheQBRWW1lYUUE
- slug: Birthday-Puja-English-Talk
  title: Birthday Puja English Talk
  video_ref: r1XVtAUUxVQ0BOB0hcSBpUW1lYUUE
other_languages:
- mr
