title: 'Sahasrara puja: Attain that Sahaja state'
date: '2000-05-07'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/2000/05/07/sahastrara-puja-2000/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  vimeo_url: https://vimeo.com/153497349/23f8d62fd2
- slug: Sahasrara-Puja-Talk-Attain-That-Sahaja-State
  title: 'Sahasrara Puja Talk: Attain That Sahaja State'
  vimeo_url: https://vimeo.com/153497679/64cc8d8fc8
