title: 'Sahasrara puja: Attain that Sahaja state'
date: '2000-05-07'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/2000/05/07/sahastrara-puja-2000/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  video_ref: r1VwgSW0IGTRUeU0hWTR5WU1VbVEI
- slug: Sahasrara-Puja-Talk-Attain-That-Sahaja-State
  title: 'Sahasrara Puja Talk: Attain That Sahaja State'
  video_ref: r1XQ8SURBaFhAZV0hWThtWU1VbVEI
