title: Feel the cool breeze of the Holy Ghost coming out of your head
date: '1987-11-05'
location: Madrid (Spain)
amruta_url: https://www.amruta.org/1987/11/05/1st-public-program-in-madrid-1987/
language: en
videos:
- slug: Feel-The-Cool-Breeze-Of-The-Holy-Ghost-Coming-Out-Of-Your-Head
  title: Feel The Cool Breeze Of The Holy Ghost Coming Out Of Your Head
  video_ref: r1Bw9EWBFaTRIVUkhbTBVWWVRaUEQ
