title: 'Sahasrara Puja: How it was decided'
date: '1988-05-08'
location: Fregene (Italy)
amruta_url: https://www.amruta.org/1988/05/08/sahasrara-puja-1988/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  video_ref: r1X0UMTFtFRRhYAkBBGVNaWFxZSw
- slug: Sahasrara-Puja-Talk
  title: Sahasrara Puja Talk
  video_ref: r1WEZcQwMQQBhVVUBPHVlTUV1ZSw
