title: Seminar Day 2, Attention and Joy
date: '1977-01-27'
location: Bordi (India)
amruta_url: https://www.amruta.org/1977/01/27/attention-and-joy-bordi-1977/
language: en
videos:
- slug: 1-Seminar-Day-2
  title: 1 Seminar Day 2
  video_ref: r1EAdfRQ1MWkEQS05QXE4YU11SXVFC
