title: 'Guru Puja: Follow My Message of Love'
date: '2004-07-04'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/2004/07/04/guru-puja-2004/
language: en
videos:
- slug: Guru-Puja-Talk
  title: Guru Puja Talk
  video_ref: r1VV1AXRJbQENLAkhdShlXWFBdVkQ
- slug: Guru-Puja
  title: Guru Puja
  video_ref: r1BA1CD0UHTRAbVkheTxVWWlNdWUE
