title: 'Guru Puja: Follow My Message of Love'
date: '2004-07-04'
location: 'Campus, Cabella Ligure (Italy)'
amruta_url: https://www.amruta.org/2004/07/04/guru-puja-2004/
language: en
videos:
- slug: Guru-Puja-Talk
  title: 'Guru Puja Talk'
  video_ref: r1VV1AXRJbQENLAkhdShlXWFBdVkQ
- slug: Guru-Puja
  title: 'Guru Puja'
  video_ref: r1BA1CD0UHTRAbVkheTxVWWlNdWUE
transcript_en_base64: |
  R3VydSBQdWphLCBDYWJlbGxhIExpZ3VyZSAoSXRhbHkpLCA0IEp1bHkgMjAwNApJdCBpcyBhIGdy
  ZWF0IHBsZWFzdXJlIGZvciBtZSwgZ3JlYXRlc3Qgam95LCB0byBzZWUgc28gbWFueSBTYWhhamEg
  WW9naXMgZm9yIHRoZSBHdXJ1IHB1amEuIEl04oCZcyB2ZXJ5IGdyYXRpZnlpbmcgdG8gdGhpbmsg
  dGhhdCB0aGVyZSBhcmUgc28gbWFueSwgc28gbWFueSBvZiB5b3UsIHdobyBhcmUgZGlzY2lwbGVz
  LiBJdCB3YXMgbmV2ZXIgZXhwZWN0ZWQgdGhhdCBJ4oCZbGwgaGF2ZSBzbyBtYW55LCBzbyBtYW55
  IHBlb3BsZSBmb2xsb3dpbmcgbWUuCkl0IGlzIGJlaW5nIGV4cGVjdGVkIHRoYXQgeW91IGFsbCB3
  aWxsIGZvbGxvdyBteSBtZXNzYWdlIG9mIGxvdmUuIEkgZG8gbm90IGhhdmUgdG8gc2F5IGFueXRo
  aW5nIGZvciBsb3ZlLiBMb3ZlIGlzIFthbl0gYWJzb2x1dGUgZ2lmdCwgZ2lmdCBvZiBqdXN0IGZl
  ZWxpbmcgb3RoZXJzLiBUaGVyZSBpcyBubyB0YWxraW5nIGFib3V0IGl0LCBkaXNjdXNzaW5nIGFi
  b3V0IGl0IOKAkyBub3RoaW5nLiBKdXN0IHlvdSBmZWVsIHRoYXQgbG92ZS4gVG8gZmVlbCB0aGUg
  bG92ZSBJIHdvdWxkIHNheSBvbmUgaGFzIHRvIGhhdmUgYSBoZWFydC4gQnV0IGhvdyBjYW4geW91
  IGhhdmUgYSBoZWFydD8gSXQgaXMgbm90IHlvdXIgb3duIGRvaW5nLCBpdOKAmXMgYWxsIHRoZXJl
  LiBTbyBpdCBpcyBzb21ldGhpbmcgaXMgYWxyZWFkeSBnaWZ0ZWQgdG8geW91LCB5b3UgaGF2ZSBp
  dCwgdGhhdCB5b3UgY2FuIGZlZWwgdGhhdCBsb3ZlLiBJdOKAmXMgc28gbXVjaCBqb3ktZ2l2aW5n
  LCBwZWFjZS1naXZpbmcuCkxvdmUgaGFzIGl0cyBvd24gcXVhbGl0aWVzIGFuZCBvbmUgb2YgdGhl
  IHF1YWxpdGllcyBpcyB0aGF0IGxvdmUgdW5kZXJzdGFuZHMuIEl0cyB1bmRlcnN0YW5kaW5nIGlz
  IG5vdCBpbiB3b3Jkcywgbm90IGluIHRob3VnaHQsIGJ1dCBbaXRdIHVuZGVyc3RhbmRzIHdpdGhp
  bi4gSXQgY2FuIGZlZWwgd2l0aGluLCB3aGljaCBpcyB2ZXJ5IGltcG9ydGFudC4gVGhpcyBpcyB0
  aGUgbW9zdCBpbXBvcnRhbnQgcGFydCBvbmUgaGFzIHRvIHJlYWxpc2UsIHRoYXQgbG92ZSwgeW91
  IGNhbiBvbmx5IGZlZWwgaXQuIFlvdSBjYW5ub3QgdGFsayBhYm91dCBpdCwgeW91IGNhbm5vdCBz
  aG93IGFib3V0IGl0LCBidXQgaXQgaXMgd2l0aGluIGFuZCB5b3UgY2FuIGZlZWwgaXQuCkFuZCB0
  aGF0IGlzIHdoeSB0b2RheSBpcyB5b3VyIGNlbGVicmF0aW9uIG9mIHRoZSBHdXJ1LiBJdOKAmXMg
  dGhlIGNlbGVicmF0aW9uIHdoZXJlIHlvdSBjYW4gZmVlbCB0aGF0IGxvdmUgZm9yIHlvdXIgR3Vy
  dS4gVGhhdCBmZWVsaW5nIGlzIHdpdGhpbiwgYW5kIG9ubHkgd2l0aGluIHlvdSBjYW4gZmVlbCB0
  aGF0LiBTbyB3ZSBoYXZlIHRvIHVuZGVyc3RhbmQgW3RoYXRdIGl04oCZcyBub3QgdGhlIHNob3cu
  IEl04oCZcyBub3RoaW5nIGVsc2UgYnV0IGp1c3QgdGhlIGZlZWxpbmcgd2l0aGluIHRoYXQgeW91
  IGtub3cgdGhhdCB5b3UgaGF2ZSBsb3ZlIG9mIHRoZSBEaXZpbmUuIFRoaXMgeW91IGNhbiBoYXZl
  IGJlY2F1c2UgaXQgaXMganVzdCB0aGVyZS4gTm8gb25lIGNhbiBnaXZlIHlvdS4gTm8gb25lIGNh
  biBzZWxsIGl0LiBObyBvbmUgY2FuIHNoYXJlIGl0LiBJdOKAmXMganVzdCB0aGVyZS4gQW5kIHRo
  YXQgbG92ZSBoYXMgdG8gYmUgZmVsdCBhbmQgc2hhcmVkLiBJdCBoYXMgbm90aGluZyB0byBkbyB3
  aXRoIG90aGVycy4gV2hldGhlciBvdGhlcnMgbG92ZSB5b3Ugb3Igbm90IG1ha2VzIG5vIGRpZmZl
  cmVuY2UuIEl04oCZcyB3aXRoaW4geW91ciBTZWxmIG9ubHksIFt0aGF0XSB0aGlzIGZlZWxpbmcs
  IHRoaXMgZGVwdGggaXMgdGhlcmUsIHdoaWNoIHlvdSBlbmpveS4gSXQgaXMgdGhlIGNhcGFjaXR5
  LiBFdmVyeW9uZSBoYXMgdGhpcywgbG90cyBvZiBpdC4KU29tZXRpbWVzIHlvdSBmZWVsIHlvdSBo
  YXZlIGxvc3QgaXQsIHNvbWV0aW1lcyB5b3UgZmVlbCB5b3UgaGF2ZSBnYWluZWQgaXQsIGJ1dCBp
  dCBpcyB0aGVyZSBhcyBtdWNoIGFzIGFuIGV4cGFuc2Ugb2YgYSBzZWEuIFNlYSwgeW91IGNhbm5v
  dCBzYXksIHRvZGF5IGlzIGZ1bGwsIGFuZCB0b21vcnJvdyBpcyBub3QuIEl0IGlzIGV0ZXJuYWwu
  IEluIHRoZSBzYW1lIHdheSB0aGUgc291cmNlIG9mIHlvdXIgbG92ZSBpcyBldGVybmFsLiBZb3Ug
  Y2Fubm90IG1lYXN1cmUgaXQuIEl04oCZcyBkaWZmaWN1bHQuIEJ1dCBpdOKAmXMgYmV5b25kIGFs
  bCB5b3VyIGh1bWFuIGV4cHJlc3Npb25zIGFuZCBpdCBzaG93cyB5b3VyIHVuZGVyc3RhbmRpbmcs
  IHlvdXIgdW5kZXJzdGFuZGluZyBvZiBsb3ZlLCB3aGljaCBoYXMgbm8gd29yZHMsIHdoaWNoIGNh
  bm5vdCBleHBsYWluLiBCdXQgYnkgaXRzZWxmIHlvdSB3aWxsIGtub3cgdGhhdCwg4oCcSSBoYXZl
  IHRoaXMgcXVhbGl0eSB0byBsb3ZlIHdpdGhpbiBteXNlbGYgYW5kIEkgY2FuIGVuam95IHRoaXMg
  bG92ZSB3aXRoaW4gbXlzZWxmLuKAnQpUaGlzIGlzIGEgdmVyeSB1bmlxdWUgZ2lmdCB3aGljaCBv
  bmx5IHZlcnkgZmV3IGh1bWFuIGJlaW5ncyBoYXZlLgpBbW9uZyBhbmltYWxzLCBhbHNvLCB5b3Ug
  ZmluZCBwZW9wbGUgd2hvIGhhdmUgbG92ZS4gQnV0IHRoYXQgbG92ZSBpcyBub3QgZGVlcCwgdGhh
  dCBsb3ZlIGhhcyBubyBtZWFuaW5nLiBJdCBoYXMgc29tZSBwdXJwb3NlLCBtYXliZSwgYnV0IGl0
  IGlzIG5vdCBodW1hbiwgc28gaXQgbGFja3MgdGhlIGJlYXV0eSBvZiBodW1hbiBsb3ZlLiBJdCBs
  YWNrcyB0aGUgdW5kZXJzdGFuZGluZyBvZiBodW1hbiBsb3ZlLgpJdCBpcyBub3QgZWFzeSB0byBk
  ZXNjcmliZSBvciBleHBsYWluIGxvdmUgaW4gaHVtYW4gd29yZHMuIFRoaXMgeW91IGNhbiBvbmx5
  IGZlZWwgd2l0aGluIHlvdXJzZWxmLiBUaGF0IGlzIHdoYXQsIG9uY2UgeW91IHN0YXJ0IGZlZWxp
  bmcsIHlvdSBjYW4gZmVlbCB3aG8gaXMgeW91ciBndXJ1LCB3aG9tIGRvIHlvdSB0aGluayB5b3Ug
  YXJlIGJlaW5nIHRhdWdodCBhbmQgcGVyc3VhZGVkIGFuZCBtYWRlIHRvIGxpdmUgaW4gYSBwYXJ0
  aWN1bGFyIG1hbm5lci4KQWxsIHRoYXQgaXMgcG9zc2libGUsIGV2ZXJ5dGhpbmcgaXMgcG9zc2li
  bGUsIGh1bWFubHkgcG9zc2libGUsIGJ1dCwgdG8gbG92ZSBhbmQgdG8gZW5qb3kgbG92ZSBpcyBu
  b3Qgc28gZWFzeSB1bmxlc3MgYW5kIHVudGlsIHlvdSBhcmUgaW1tZXJzZWQgaW4gaXQuIEl04oCZ
  cyB2ZXJ5IGdyYXRpZnlpbmcsIGl0IGlzIHZlcnkgbG92YWJsZSwgdG8gc2VlIGhvdyBwZW9wbGUg
  bG92ZSBlYWNoIG90aGVyLCBhbmQgdGhlbiB0aGlzIGxvdmUgc3ByZWFkcy4gTG92ZSBiZWdldHMg
  bG92ZS4gSWYgc29tZWJvZHkgaGFzIGxvdmUgaXQganVzdCBzcHJlYWRzLiBIZSBuZWVkIG5vdCB0
  ZWxsIGFueW9uZSwgaGUgbmVlZCBub3QgY29uZmVzcyBpdCwgYnV0IGl0IHdpbGwgc3ByZWFkLiBB
  bmQgdGhpcyBpcyB3aGF0IG9uZSBoYXMgdG8gbGVhcm46IGhvdyB0byBzZWUgdGhhdCBsb3ZlIGlu
  IFt0aGVdIG90aGVyIHBlcnNvbi4KU29tZWhvdyB3ZSBhcmUgaGVyZSBhbHJlYWR5IGluIGxvdmUg
  YmVjYXVzZSBvZiBzYWhhaiBoYXBwZW5pbmcuIFdlIGFsbCBsb3ZlIGFuZCB3ZSBlbmpveSBsb3Zl
  LiBJdCBzaG93cyBvbiBvdXIgZmFjZXMsIHRoYXQgd2UgYXJlIGluIGxvdmUsIGluIG91ciBjaGFy
  YWN0ZXJzLCBpbiBvdXIgbGl2ZXMg4oCTIHRoYXQgd2UgYXJlIGluIGxvdmUuIFdoYXQgYSB0aGlu
  Zywgd2hpY2ggaXMgbm90IHZlcnkgbm9ybWFsLCBiZWNvbWVzIHNvIG5vcm1hbCBhbmQgc28gZWFz
  aWx5IGF2YWlsYWJsZSBvbmx5LgpJdCBpcyBhIHZlcnkgYmlnIGJsZXNzaW5nIHRoYXQgeW91IGFy
  ZSBodW1hbiBiZWluZ3MgYW5kIHRoYXQgdGhpcyBzb3VyY2Ugb2YgbG92ZSBpcyB0aGVyZSBwbHVz
  IHRoZSBmZWVsaW5nIGZvciBsb3ZlIGlzIHRoZXJlLiBJdOKAmXMgYSB2ZXJ5IGludHJpY2F0ZSBz
  aXR1YXRpb24gd2hpY2ggY2Fubm90IGJlIGV4cGxhaW5lZCBpbiB3b3Jkcywgb25seSBvbmUgY2Fu
  IGJlIGluIGl0IGFuZCBlbmpveSBpdC4KTm93IHRvZGF5IGlzIGEgZGF5IHdoZW4gd2UgYXJlIGNl
  bGVicmF0aW5nIHRoZSBHdXJ1IFB1amEuIFRoZSBncmVhdGVzdCBHdXJ1IHRoYXQgd2UgaGF2ZSBp
  cyBsb3ZlLCBTYWhhaiBsb3ZlLCBpcyB0aGUgR3VydSB3aXRoaW4gdXMsIHdoaWNoIHRlYWNoZXMg
  dXMsIHdoaWNoIHNvbWVob3cgb3Igb3RoZXIgbGVhZHMgdXMuIFdlIGFyZSBsZWQgaW50byB0aGF0
  IGdyZWF0IGxpbmUgb2YgdW5kZXJzdGFuZGluZyBmb3Igd2hpY2ggd2UgZG9u4oCZdCBoYXZlIHRv
  IGdvIHRvIGFueSBjb2xsZWdlLCB0byBhbnkgc2Nob29sIGZvciBlZHVjYXRpb24uIEl0IGlzIHNv
  bWV0aGluZyBzbyBtdWNoIHdpdGhpbiB0aGF0IGl0IHdvcmtzIGFuZCBleHByZXNzZXMgaXRzZWxm
  LCBleHByZXNzZXMgbGlrZSBsaWdodC4gU3VjaCBwZW9wbGUgd2UgY2FuIG1ha2Ugb3V0IGJlY2F1
  c2UgdGhleSBhcmUgZnVsbHkgZW5saWdodGVuZWQuIFRoZXkgaGF2ZSBsaWdodCBhbmQgdGhyb3Vn
  aCB0aGF0IGxpZ2h0IHRoZXkgc2VlIHRoZSB3aG9sZSB3b3JsZCwgd2hpY2ggaXMgdmVyeSBpbm5v
  Y2VudCBhbmQgc2ltcGxlIGZvciB0aGVtLgpXZSBoYXZlIGxvdmUgZm9yIG91ciBjaGlsZHJlbiwg
  bmF0dXJhbGx5LiBXZSBoYXZlIGxvdmUgZm9yIG91ciBwYXJlbnRzLCBuYXR1cmFsbHkuIFdlIGhh
  dmUgbG92ZSBmb3Igc29tZSBwZW9wbGUgYnV0IHRoYXQgbG92ZSBpcyBkaWZmZXJlbnQgZnJvbSB3
  aGF0IGxvdmUgSSBhbSB0ZWxsaW5nIHlvdS4gVGhhdCBoYXMgc29tZSBjb25uZWN0aW9ucywgc29t
  ZSBtZWFuaW5ncywgYnV0IHRoaXMgbG92ZSB3aGljaCBpcyDigJMgY2Fubm90IGJlIGRlc2NyaWJl
  ZCBpbiB3b3JkcywgaGFzIHRvIGJlIGZlbHQgd2l0aGluLgpTYW1lIHdoZW4geW91IHRhbGsgb2Yg
  eW91ciBHdXJ1IHlvdSBzaG91bGQgaGF2ZSB0aGF0IGxvdmUgd2l0aGluIHlvdS4gV2h5IGRvIHlv
  dSBmZWVsIHNvIG11Y2g/IFRoZSByZWFzb24gaXMgR3VydSBsb3ZlcyB5b3UgYW5kIHlvdSBsb3Zl
  IEd1cnUuIFRoYXTigJlzIHRoZSBvbmx5IHJlYXNvbiB3aHkgc2hvdWxkIHlvdSBsb3ZlIHlvdXIg
  R3VydS4gTm93IHRoZXJl4oCZcyBubyByZWFzb24gZm9yIHRoYXQuIEJlY2F1c2UgbG92ZSBpcyBs
  b3ZlLiBUaGF0IGlzIGhvdyB0aGUgR3VydSBiZWNvbWVzIHZlcnkgaW1wb3J0YW50IGluIGxpZmUu
  IFdlIGhhdmUgcGVvcGxlIHdobyBsb3ZlIHRoZWlyIEd1cnUgYW5kIGFyZSB2ZXJ5IG11Y2ggaW4g
  Y2hhc3RlIHVuZGVyc3RhbmRpbmcgb2YgdGhlaXIgbG92ZS4KSW4gdGhpcyBncmVhdCBvcHBvcnR1
  bml0eSBvZiBsb3ZlIHRoYXQgd2UgYXJlLCB3ZSBhcmUgaGVyZSB0byBlbmpveSBlYWNoIG90aGVy
  IGZ1bGx5IGZyb20gb3VyIGhlYXJ0LiBUaGF0IHRoZXJlIGlzIHRoaXMgb2NlYW4gd2l0aGluIHVz
  LiBXZSBoYXZlIHRvIGp1c3QgZ2V0IHN1Ym1lcmdlZCBpbiB0aGF0IG9jZWFuLiBJZiB3ZSBhcmUg
  bG9zdCBpbiB0aGF0IG9jZWFuIHRoZW4gd2XigJlsbCBoYXZlIG5vIHByb2JsZW1zLCBubyBxdWVz
  dGlvbnMsIGV2ZXJ5dGhpbmcgd2lsbCBiZSBvdXIgb3duLCBhbmQgd2UgY2FuIG1hbmFnZSBldmVy
  eXRoaW5nIHdpdGhvdXQgYW55IGFyZ3VtZW50LCB3aXRob3V0IGFueSBxdWVzdGlvbmluZy4gVGhh
  dCBpcyB3aGF0IGlzIGJlaW5nIFNhaGFqLgpUaGUgU2FoYWogd2F5IGlmIHlvdSBoYXZlLCB0aGlz
  IGxvdmUgeW91IGVuam95LiBZb3UgZW5qb3kgeW91cnNlbGYgYW5kIGVuam95IGV2ZXJ5Ym9keSBl
  bHNlLCBiZWNhdXNlIGl0IGlzIFNhaGFqLiBEb27igJl0IGhhdmUgdG8gbWFrZSBhbnkgZWZmb3J0
  cywgZG9u4oCZdCBoYXZlIHRvIHRyeSBhbnl0aGluZywganVzdCBpdCBpcyB0aGVyZSBhbmQgaXQg
  d29ya3MuClRoZSBmZWVsaW5nIG9mIGxvdmUgaGFzIG5vIHdheSBvZiBleHByZXNzaW5nIGl0c2Vs
  Zi4gSXQgaXMganVzdCB0aGVyZS4gSXQgY2Fubm90IGV4cHJlc3MsIGJlY2F1c2UgaXQgaXMgd2l0
  aG91dCBleHByZXNzaW9uLiBJdCBpcyBqdXN0IHRvIGJlIGZlbHQgd2l0aGluIHlvdXJzZWxmLiBU
  aGVuIHlvdSB3YW50IHRvIGRvIHNvIG1hbnkgdGhpbmdzOiB5b3Ugd2FudCB0byBoZWxwIGV2ZXJ5
  b25lLCB5b3Ugd2FudCB0byBoZWxwIHlvdXJzZWxmLCB5b3Ugd2FudCB0byBkbyBnb29kIHRvIG90
  aGVycy4KU28gbXVjaCBoYXMgYmVlbiBkb25lIGJ5IGdyZWF0IGxlYWRlcnMgb2YgdGhlIHdvcmxk
  LCBiZWNhdXNlIHRoZXkgaGFkIHRoYXQgbG92ZS4gVGhleSBoYWQgbm90aGluZyBlbHNlIGJ1dCB0
  aGlzIGxvdmUsIHdoaWNoIHRoZXkgY291bGQgbm90IGNvbnRhaW4gdGhlbSB3aXRoaW4gdGhlbXNl
  bHZlcywgc28gdGhleSB0cmllZCB0byBzcHJlYWQgaXQgYW5kIHRoZXkgYXJlIGNhbGxlZCBub3cg
  YXMgb3VyIGd1cnUsIGFzIG91ciBtYXN0ZXJzLiBJdOKAmXMgdGhhdCBsb3ZlIHdpdGhpbiB3aGlj
  aCBhcHByb2FjaGVkIHBlb3BsZSBpbiB0aGF0IHVuaXF1ZSBtYW5uZXIuIFRoYXTigJlzIGEgdGhp
  bmcgdGhhdCB3ZSBjYW5ub3QgcG9zc2VzcywgeW91IGNhbm5vdCBjbGFpbS4gSXQgaXMgdGhlcmUg
  YW5kIGl0IHdvcmtzLiBJdCB3b3JrcyBhdXRvbWF0aWNhbGx5LiBUaGlzIGlzIHdoYXQgd2UgaGF2
  ZSB0byBrbm93IHRoYXQgd2UgYXJlIHRoYXQgbG92ZS4gVGhhdCBsb3ZlIGlzIHdpdGhpbiB1cywg
  d2UgaGF2ZSB0byBoYXZlIGtub3dsZWRnZSwgd2UgaGF2ZSB0byBoYXZlIGEgY29tcGxldGUga25v
  d2xlZGdlIHRoYXQgd2UgYXJlIHRoYXQgbG92ZS4gVGhhdCB3aWxsIHNvbHZlIG91ciBwcm9ibGVt
  LiBCZWNhdXNlIHlvdSBjYW4gZXhwbGFpbiBldmVyeXRoaW5nLCBhbGwgeW91ciBiZWhhdmlvdXIs
  IGFsbCB5b3VyIGZhaWx1cmVzLiBFdmVyeXRoaW5nIHlvdSBjYW4gZXhwbGFpbiB3aGVuIHlvdSBr
  bm93IHRoYXQgeW91IGFyZSBlbmRvd2VkIHdpdGggdGhhdCBsb3ZlLgpUaGlzIGlzIHdoYXQgaXMg
  dGhlIEd1cnUsIGlzIHRoZSBsb3ZlIHdpdGhpbiB5b3UsIHdoaWNoIHdhbnRzIHRvIHNoYXJlIGxv
  dmUgd2l0aCBvdGhlcnMsIHdoaWNoIHdhbnRzIHRvIGdpdmUgbG92ZSB0byBvdGhlcnMuIFRoaXMg
  aXMgd2hhdCBpcyBwZWFjZSBhbmQgam95LgpJIGNhbiBnbyBvbiB0YWxraW5nIG9uIGxvdmUsIGJ1
  dCB0byBmZWVsIGl0IHdpdGhpbiB5b3Vyc2VsZiBpcyB0aGUgYmlnZ2VzdCB0aGluZy4gTGlrZSB3
  YXRlci4gSWYgeW91IGFyZSB0aGlyc3R5LCB3ZSBjYW4gZ2l2ZSB5b3Ugd2F0ZXIg4oCTIGJ1dCB3
  ZSBjYW5ub3QgZHJpbmshIFlvdSBoYXZlIHRvIGRyaW5rIHdhdGVyIGFuZCB5b3UgaGF2ZSB0byBm
  ZWVsIHRoZSB0YXN0ZSwgZmVlbCB0aGUgZmVlbGluZywgd2hhdCBpdCBkb2VzLCBhbmQgYWxsIHRo
  YXQgaXMgdG9nZXRoZXIsIHRoYXTigJlzIG5vdCBzZXBhcmF0ZS4KSSBkb27igJl0IHRoaW5rIHRo
  ZSBzdWJqZWN0IHdhcyB0b28gc3VidGxlIGZvciB5b3UgcGVvcGxlLiBZb3UgYWxsIGhhdmUgcmVh
  Y2hlZCBhIGNlcnRhaW4gYW1vdW50IG9mIHVuZGVyc3RhbmRpbmcgb2YgdGhhdCBsb3ZlLiBJIGhv
  cGUgaXQgZ3Jvd3MgYW5kIHlvdSBncm93IGludG8gaXQsIGFsbCBvZiB5b3UgYW5kIGVuam95IGl0
  LgpNYXkgR29kIGJsZXNzIHlvdSE=
