title: Evening Program and Talk to Sahaja Yogis The Day after Mahashivaratri Puja
date: '1992-03-01'
location: Glenrock Scout Camp, Newcastle (Australia)
amruta_url: https://www.amruta.org/1992/03/01/day-after-shivaratri-puja-1992/
language: en
videos:
- slug: Advice-to-Yogis
  title: Advice to Yogis
  video_ref: r1B19MDEADFktOWEhaSx1UU1BfVkQ
- slug: Evening-After-Maha-Shiva-Puja
  title: Evening After Maha Shiva Puja
  video_ref: r1BA8XUEJQFBAdWUhbTRlVU1BfVkQ
