title: Evening Program and Talk to Sahaja Yogis The Day after Mahashivaratri Puja
date: '1992-03-01'
location: Glenrock Scout Camp, Newcastle (Australia)
amruta_url: https://www.amruta.org/1992/03/01/day-after-shivaratri-puja-1992/
language: en
videos:
- slug: Advice-to-Yogis
  title: Advice to Yogis
  vimeo_url: https://vimeo.com/777195025/9c8ca4e83b
- slug: Evening-After-Maha-Shiva-Puja
  title: Evening After Maha Shiva Puja
  vimeo_url: https://vimeo.com/777194444/80ca269cca
