title: 'Diwali Puja: Remove all the darkness of Kali Yuga'
date: '1999-11-07'
location: Camping Apollon, Delphi (Greece)
amruta_url: https://www.amruta.org/1999/11/07/diwali-puja-1999/
language: en
videos:
- slug: Diwali-Puja
  title: Diwali Puja
  video_ref: r1U1UWUBBSEBZJV0hXTxhXWVFaVEA
- slug: Diwali-Puja-Talk-Remove-all-the-darkness-of-Kali-Yuga
  title: 'Diwali Puja Talk: Remove all the darkness of Kali Yuga'
  video_ref: r1VVVEWhFbQxBMVEhZTBxXWVFaVEA
