title: 'Diwali Puja: Remove all the darkness of Kali Yuga'
date: '1999-11-07'
location: Camping Apollon, Delphi (Greece)
amruta_url: https://www.amruta.org/1999/11/07/diwali-puja-1999/
language: en
videos:
- slug: Diwali-Puja
  title: Diwali Puja
  vimeo_url: https://vimeo.com/352036568/6dee0d9b96
- slug: Diwali-Puja-Talk-Remove-all-the-darkness-of-Kali-Yuga
  title: 'Diwali Puja Talk: Remove all the darkness of Kali Yuga'
  vimeo_url: https://vimeo.com/352036156/5ac69e3090
