title: Subconscious, Supraconscious and Our Correct Ideals
date: '1981-05-24'
location: Chelsham Road Ashram, London (England)
amruta_url: https://www.amruta.org/1981/05/24/subconscious-supraconscious-and-our-correct-ideals-chelsham-1981/
language: en
videos:
- slug: You-Are-Your-Own-Ideals-London-NITL-HD
  title: You Are Your Own Ideals London NITL HD
  video_ref: r1XFVGDBdVQhdPAkhWSRVWWVhbUks
