title: 7th Day of Navaratri, You all should depend on Paramchaitanya
date: '1998-09-27'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1998/09/27/navaratri-puja-1998/
language: en
videos:
- slug: Navaratri-Puja-Cabella-Italy-DP-RAW
  title: Navaratri Puja Cabella Italy DP-RAW
  vimeo_url: https://vimeo.com/1002712878/de5c0ea61d
- slug: Navaratri-Puja-Talk
  title: Navaratri Puja Talk
  vimeo_url: https://vimeo.com/333503883/2b3f00662c
