title: 'Sahasrara Puja: Blessing of Divine Pours Only If Sahasrara is Completely Open'
date: '1998-05-10'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1998/05/10/sahastrara-puja-1998/
language: en
videos:
- slug: Sahasrara-Puja-Talk
  title: Sahasrara Puja Talk
  video_ref: r1X0BdFQBGQR9UBUBOGVdfUF1ZSw
  sync: primary
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  video_ref: r1XhAMRAAXRhhSU0BIGVVdVVxZSw
  sync: derived
