title: 'Adi Kundalini Puja: The Advent Of Primordial Kundalini'
date: '1990-06-19'
location: Moedling (Austria)
amruta_url: https://www.amruta.org/1990/06/19/shri-kundalini-puja-modling-1990/
language: en
videos:
- slug: Adi-Kundalini-Puja-Talk-The-Advent-Of-Primordial-Kundalini
  title: 'Adi Kundalini Puja Talk: The Advent Of Primordial Kundalini'
  video_ref: r1A1hCUUFaFhZLVkhfThlSXlJfUkI
  sync: derived
- slug: Adi-Kundalini-Puja
  title: Adi Kundalini Puja
  video_ref: r1U1hNW0VSFxUYBEhdSRpYXlJfUkI
  sync: primary
