title: Our Understanding of Sahaja Yoga, Seminar
date: '1978-12-09'
location: London (England)
amruta_url: https://www.amruta.org/1978/12/09/our-understanding-of-sahaja-yoga-uk-1978/
language: en
videos:
- slug: Our-Understanding-of-SY
  title: Our Understanding of SY
  vimeo_url: https://vimeo.com/1053736525/a248f79996
