title: Advice at Bharatiya Vidya Bhavan
date: '1977-03-22'
location: Mumbai (India)
amruta_url: https://www.amruta.org/1977/03/22/advice-at-bharatiya-vidya-bhavan-1977/
language: en
videos:
- slug: Advice
  title: Advice
  vimeo_url: https://vimeo.com/771453084/9d5e208370
