title: From Mooladhara to Void
date: '1982-07-10'
location: Guildhall Theatre, Derby (England)
amruta_url: https://www.amruta.org/1982/07/10/from-mooladhara-to-void-derby-1982/
language: en
videos:
- slug: From-Mooladhara-to-Void
  title: From Mooladhara to Void
  vimeo_url: https://vimeo.com/88520478/bcd4b6a30e
- slug: QA-after-the-Talk
  title: Q&A after the Talk
  vimeo_url: https://vimeo.com/88503628/fc7adc67cd
