title: From Mooladhara to Void
date: '1982-07-10'
location: Guildhall Theatre, Derby (England)
amruta_url: https://www.amruta.org/1982/07/10/from-mooladhara-to-void-derby-1982/
language: en
videos:
- slug: From-Mooladhara-to-Void
  title: From Mooladhara to Void
  video_ref: r1CURaFVQXR0kCBUBBGlVaU11ZSw
- slug: QA-after-the-Talk
  title: Q&A after the Talk
  video_ref: r1CBdeQgEREhoCAUBBH1dZUV1ZSw
