title: 'Easter Puja: Materialism'
date: '1987-04-19'
location: Ashram of Pichini, Rome (Italy)
amruta_url: https://www.amruta.org/1987/04/19/easter-puja-1987/
language: en
videos:
- slug: Easter-Puja
  title: Easter Puja
  video_ref: r1Bl0WWkABE0UYVUhXTBRSWVlbV0I
- slug: Easter-Puja-Talk
  title: Easter Puja Talk
  video_ref: r1VQlMCxJXR0QUAkhbQR1SWVlbV0I
