title: 'Easter Puja: Materialism'
date: '1987-04-19'
location: Ashram of Pichini, Rome (Italy)
amruta_url: https://www.amruta.org/1987/04/19/easter-puja-1987/
language: en
videos:
- slug: Easter-Puja
  title: Easter Puja
  vimeo_url: https://vimeo.com/163833958/456fc43b1c
- slug: Easter-Puja-Talk
  title: Easter Puja Talk
  vimeo_url: https://vimeo.com/163833084/c9725fb8e0
