title: 'Navaratri Puja: Develop Wisdom Through Meditation, Bhakti & Shraddha'
date: '2002-10-27'
location: Lake Piru Recreational Area Campground, Ventura County (United States)
amruta_url: https://www.amruta.org/2002/10/27/navaratri-puja-2002/
language: en
videos:
- slug: Navaratri-Puja
  title: Navaratri Puja
  video_ref: r1XFgVXRABQBEcV0hdTxhVW1JZVEE
- slug: Navaratri-Puja-Talk
  title: Navaratri Puja Talk
  video_ref: r1UFRGXhFXRhceWUhaTRRSWlJZVEE
