title: 'Navaratri Puja: Develop Wisdom Through Meditation, Bhakti & Shraddha'
date: '2002-10-27'
location: Lake Piru Recreational Area Campground, Ventura County (United States)
amruta_url: https://www.amruta.org/2002/10/27/navaratri-puja-2002/
language: en
videos:
- slug: Navaratri-Puja
  title: Navaratri Puja
  vimeo_url: https://vimeo.com/251314562/61b5cd4a49
- slug: Navaratri-Puja-Talk
  title: Navaratri Puja Talk
  vimeo_url: https://vimeo.com/251303945/83d35e7285
