title: 'Adi Shakti puja: Mother, make me such that I suck more of the Divine'
date: '1982-08-01'
location: Cowley Manor, Cheltenham (England)
amruta_url: https://www.amruta.org/1982/08/01/shri-adi-shakti-puja-1982/
language: en
videos:
- slug: Adi-Shakti-Puja-Cheltenham-UK-DP
  title: Adi Shakti Puja Cheltenham UK DP
  video_ref: r1BFoRC0dTQxZIAkhZQBxXW1hcUUI
- slug: Babies-receive-names-Cheltenham-UK-DP
  title: Babies receive names Cheltenham UK DP
  video_ref: r1V1sXCEcDF0IbAEhZTxVUW1hcUUI
- slug: Mantras-used-before-Puja-Cheltenham-UK-DP
  title: Mantras used before Puja Cheltenham UK DP
  video_ref: r1XVsVUENbEEJLVkhdTRVUW1hcUUI
- slug: Adi-Shakti-Puja-Talk-Cheltenham-UK-DP
  title: Adi Shakti Puja Talk Cheltenham UK DP
  video_ref: r1VFVHWUYGExEVBEhaSxVUW1hcUUI
