title: 'Adi Shakti puja: Mother, make me such that I suck more of the Divine'
date: '1982-08-01'
location: Cowley Manor, Cheltenham (England)
amruta_url: https://www.amruta.org/1982/08/01/shri-adi-shakti-puja-1982/
language: en
videos:
- slug: Adi-Shakti-Puja-Cheltenham-UK-DP
  title: Adi Shakti Puja Cheltenham UK DP
  vimeo_url: https://vimeo.com/104916196/cee613be6a
- slug: Babies-receive-names-Cheltenham-UK-DP
  title: Babies receive names Cheltenham UK DP
  vimeo_url: https://vimeo.com/104915866/a61ba3ac72
- slug: Mantras-used-before-Puja-Cheltenham-UK-DP
  title: Mantras used before Puja Cheltenham UK DP
  vimeo_url: https://vimeo.com/104915842/7f1e979a78
- slug: Adi-Shakti-Puja-Talk-Cheltenham-UK-DP
  title: Adi Shakti Puja Talk Cheltenham UK DP
  vimeo_url: https://vimeo.com/104915825/e8bfd20391
