title: 'Shri Virata and Viratangana Puja:  I have to have 16,000 children'
date: '1993-10-10'
location: YMCA Camp Whittle, Fawnskin (United States)
amruta_url: https://www.amruta.org/1993/10/10/shri-virata-puja-los-angeles-1993/
language: en
videos:
- slug: Viratagana-Puja-Los-Angeles-USA-DP-RAW
  title: Viratagana Puja Los Angeles USA DP-RAW
  video_ref: r1UF8XWU1UFhZPWUhdTxVRUlFQWEs
  sync: primary
- slug: Viratagana-Puja-Talk-Los-Angeles-USA-DP-RAW
  title: Viratagana Puja Talk Los Angeles USA DP-RAW
  video_ref: r1Bl5FC0EHRBdMVUhcSxVRUlFQWEs
  sync: derived
