title: 'Shri Vishnumaya Puja: She has created a big maya'
date: '1987-08-09'
location: YWCA Camp, Pawling (United States)
amruta_url: https://www.amruta.org/1987/08/09/shri-vishnumaya-puja-new-york-1987/
language: en
videos:
- slug: Vishnumaya-Puja
  title: Vishnumaya Puja
  video_ref: r1ChFbTABDER5RU0BNG1hTWVxZSw
- slug: Vishnumaya-Puja-Talk
  title: Vishnumaya Puja Talk
  video_ref: r1WkNbRAFMFhtUUkBBHVRaUF1ZSw
