title: 'Birthday Puja Talk: Guarding Against Slothfulness'
date: '1980-03-23'
location: 4A Castletown Rd, London (England)
amruta_url: https://www.amruta.org/1980/03/23/birthday-puja-1980/
language: en
videos:
- slug: Birthday-Puja
  title: Birthday Puja
  video_ref: r1FlRdFgxEURcWHU5UXkgVU11SXVFC
