title: 'Sahasrara Puja: You Have All Become Mahayogis Now'
date: '1990-05-06'
location: Fiuggi (Italy)
amruta_url: https://www.amruta.org/1990/05/06/sahasrara-puja-you-have-all-become-mahayogis-now-and-concert-with-talk/
language: en
videos:
- slug: Sahasrara-Puja-1
  title: Sahasrara Puja 1
  video_ref: r1AA0VXUMHTEoZA0haShVWW1ZdUkQ
- slug: Sahasrara-Puja-2
  title: Sahasrara Puja 2
  video_ref: r1AFhECEEDFkIYV0hYTBpQWlFdUkQ
