title: 'Sahasrara Puja: You Have All Become Mahayogis Now'
date: '1990-05-06'
location: Fiuggi (Italy)
amruta_url: https://www.amruta.org/1990/05/06/sahasrara-puja-you-have-all-become-mahayogis-now-and-concert-with-talk/
language: en
videos:
- slug: Sahasrara-Puja-1
  title: Sahasrara Puja 1
  vimeo_url: https://vimeo.com/735717835/b499e74aae
- slug: Sahasrara-Puja-2
  title: Sahasrara Puja 2
  vimeo_url: https://vimeo.com/735001757/651ca5a04e
